### ISSUE TITLE
Create graph from output database ( SourceID distribution)

### ISSUE THREAD

**Issue by tangent-tz** [tangent-tz/reCreate#8]
Title : SourceID distribution
DB name: movesactivityoutput
X-axis: SourceID
Y-axis: Activity for activityID=6
Graph type: Bar chart

![image](https://github.com/tangent-tz/reCreate/assets/71015600/148baf33-9644-4cdc-a955-1e14ec5ee202)

**Comment by MahaSFU** [comment]
Hi Tanzil 
Any updates here ?

**Comment by tangent-tz** [comment]
Yep this should be done
